# Generated by Django 4.2.6 on 2024-10-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_application_history',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('application_date', models.DateField(blank=True, default=None, null=True)),
                ('applicant_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ca_authority', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('service_id', models.IntegerField(blank=True, default=None, null=True)),
                ('application_status', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('action_date', models.DateField(blank=True, default=None, null=True)),
                ('actor_id', models.IntegerField(blank=True, default=None, null=True)),
                ('actor_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_inspection_monitoring_t1',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('inspection_type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('inspection_date', models.DateField(blank=True, default=None, null=True)),
                ('inspection_reason', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ec_clearance_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('login_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('proponent_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('project_name', models.TextField(blank=True, default=None, max_length=250, null=True)),
                ('address', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('observation', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('team_leader', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('team_members', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('remarks', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('fines_penalties', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_by_ca', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('record_status', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('inspection_reference_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_on', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
