# Generated by Django 4.2.6 on 2025-07-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_application_history',
            name='service_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
