# Generated by Django 2.2 on 2023-07-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_application_history',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('application_date', models.DateField(blank=True, default=None, null=True)),
                ('applicant_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ca_authority', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('service_id', models.IntegerField(blank=True, default=None, null=True)),
                ('application_status', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('action_date', models.DateField(blank=True, default=None, null=True)),
                ('actor_id', models.IntegerField(blank=True, default=None, null=True)),
                ('actor_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, default=None, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='t_inspection_monitoring_t1',
            name='inspection_reference_no',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_inspection_monitoring_t1',
            name='updated_on',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_inspection_monitoring_t1',
            name='login_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
