# Generated by Django 4.1.3 on 2023-03-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_inspection_monitoring_t1',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('inspection_type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('inspection_date', models.DateField(blank=True, default=None, null=True)),
                ('inspection_reason', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ec_clearance_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('login_id', models.IntegerField(blank=True, default=None, null=True)),
                ('proponent_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('project_name', models.TextField(blank=True, default=None, max_length=250, null=True)),
                ('address', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('observation', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('team_leader', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('team_members', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('remarks', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('fines_penalties', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('status', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('updated_by_ca', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('record_status', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
        ),
    ]
