"""
Django settings for ECS project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!y+j-du+@82@b*2^^%fq84f!=&$rd#o3=vbg6!p2xhmda4&rgf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','192.168.30.215','192.168.30.151','192.168.30.155', '192.168.134.31','localhost','staging-datahub-apim.dit.gov.bt', '172.30.78.130','192.168.0.111', '6961-118-103-141-153.ngrok-free.app','192.168.218.31']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ecs_admin',
    'crispy_forms',
    'proponent',
    'ecs_main',
    'report',
    'corsheaders',
    'django_celery_beat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True  # Change to True if you want to allow all origins
CORS_ORIGIN_WHITELIST = [
    'http://localhost:8000',  # Add your allowed origins here
    'https://staging.bhutanndi.com',
    # Add more origins as needed
]
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',  # Add your client-side application URL here

    # Add more origins as needed
]
CORS_ALLOW_CREDENTIALS = True


ROOT_URLCONF = 'ECS.urls'

ASGI_APPLICATION = "ECS.asgi.application"

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'ndi-proof-cache',
    }
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ECS.wsgi.application'

EC_PUBLIC_TOKEN = "ecss_2026_secure_X9kLmP78"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Laptop / local dev: HOST = 'localhost'
# Production (app server): change HOST to your database server IP or hostname
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ecs_db',
        'USER': 'postgres',
        'PASSWORD': 'Sp@rklesecss@2022',
        'HOST': '172.30.69.10',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

LOGIN_URL = 'index'

os.environ["NDI_NATS_SEED"] = "SUAPXY7TJFUFE3IX3OEMSLE3JFZJ3FZZRSRSOGSG2ANDIFN77O2MIBHWUM"
os.environ["NATS_SERVER_URL"] = "nats://13.229.203.54:4222"
NATS_SERVER_URL = "nats://13.229.203.54:4222"
NDI_NATS_SEED = "SUAPXY7TJFUFE3IX3OEMSLE3JFZJ3FZZRSRSOGSG2ANDIFN77O2MIBHWUM"

# Bhutan NDI integration (demo environment)
NDI_ENVIRONMENT = 'demo'
NDI_VERIFIER_BASE = 'https://demo-client.bhutanndi.com'
NDI_WEBHOOK_ID = 'ecssserverid'
# On mobile, show QR below the deep link button (scan with demo wallet if needed)
NDI_MOBILE_SHOW_QR_ALSO = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_BACKEND = 'ecs_admin.backends.email_backend.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'systems@moenr.gov.bt'
EMAIL_HOST_PASSWORD = 'wdiigzpprtutwmdc'



#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True
#EMAIL_HOST_USER = 'sparkletechnologies0509@gmail.com'
#EMAIL_HOST_PASSWORD = 'htosvqmtrozajpey'

NATS_SERVER_URL = 'nats://13.229.203.54:4222'

MEDIA_ROOT =  os.path.join(BASE_DIR, 'attachments')
MEDIA_URL = '/attachments/'


# ============================================================
# ✅ CELERY CONFIGURATION
# ============================================================
from celery.schedules import crontab

# Broker — Redis running on localhost
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# ✅ Timezone
CELERY_TIMEZONE = 'Asia/Thimphu'   # Bhutan Standard Time (UTC+6)
CELERY_ENABLE_UTC = False          # ✅ Use local time, NOT UTC
USE_TZ = True

# ✅ Periodic task schedule
CELERY_BEAT_SCHEDULE = {
    'send-ai-reminders-daily': {
        'task': 'ecs_admin.tasks.send_additional_info_reminder',
        'schedule': crontab(hour=22, minute=14),   # 8 AM Thimphu time
    },
}

