# Generated by Django 4.1.3 on 2023-02-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_ec_industries_t5_raw_materials',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('raw_material', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('qty', models.IntegerField(blank=True, default=None, null=True)),
                ('source', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('storage_method', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='t_ec_industries_t5_raw_materails',
        ),
        migrations.RenameField(
            model_name='t_ec_industries_t1_general',
            old_name='Industrial_area_acre',
            new_name='industrial_area_acre',
        ),
    ]
