# Generated by Django 3.1.7 on 2023-04-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_report_submission_t1',
            old_name='Initiatives_undertaken',
            new_name='initiatives_undertaken',
        ),
        migrations.RenameField(
            model_name='t_report_submission_t2',
            old_name='action_undertaken',
            new_name='action_taken',
        ),
        migrations.RemoveField(
            model_name='t_ec_renewal_t2',
            name='precord_id',
        ),
        migrations.RemoveField(
            model_name='t_report_submission_t1',
            name='report_year',
        ),
        migrations.RemoveField(
            model_name='t_report_submission_t2',
            name='ec_clearance_no',
        ),
        migrations.RemoveField(
            model_name='t_report_submission_t2',
            name='precord_id',
        ),
        migrations.AddField(
            model_name='t_report_submission_t1',
            name='ca_authority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_report_submission_t1',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_report_submission_t1',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_report_submission_t1',
            name='report_reference_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_report_submission_t1',
            name='report_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='t_report_submission_t1',
            name='submission_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_report_submission_t2',
            name='report_reference_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_report_submission_t1',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_report_submission_t1',
            name='ec_clearance_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_report_submission_t1',
            name='proponent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_report_submission_t1',
            name='report_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
