# Generated by Django 4.1.3 on 2023-04-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_ec_industries_t11_ec_details',
            old_name='ec_content',
            new_name='ec_terms',
        ),
        migrations.RenameField(
            model_name='t_ec_renewal_t1',
            old_name='ec_clearance_no',
            new_name='ec_referene_no',
        ),
        migrations.AddField(
            model_name='t_ec_industries_t11_ec_details',
            name='ec_reference_no',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_renewal_t2',
            name='ec_referene_no',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
