# Generated by Django 4.2.6 on 2025-11-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general_audit',
            name='activity',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
