# Generated by Django 2.2 on 2023-05-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_ec_industries_t12_drainage_details',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('drain_type', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('chainage', models.CharField(blank=True, default=None, max_length=250, null=True)),
            ],
        ),
    ]
