# Generated by Django 4.2.6 on 2024-07-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='revocation_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
