# Generated by Django 4.1.3 on 2023-04-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='application_source',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='t_workflow_dtls',
            name='application_source',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
