# Generated by Django 4.2.6 on 2025-11-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0002_t_ec_industries_t1_general_audit_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='activity',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
