# Generated by Django 4.1.3 on 2023-02-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0002_t_ec_industries_t5_raw_materials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_ec_industries_t8_forest_produce',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('produce_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('qty', models.IntegerField(blank=True, default=None, null=True)),
                ('storage_method', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='t_ec_industries_t1_general',
            old_name='en_air_pollution_control_pcd_dimention',
            new_name='en_air_pollution_control_pcd_dimension',
        ),
        migrations.RenameField(
            model_name='t_ec_industries_t1_general',
            old_name='en_pol_control_device_dimention',
            new_name='en_pol_control_device_dimension',
        ),
        migrations.RenameField(
            model_name='t_ec_industries_t1_general',
            old_name='en_pol_control_device_stack_heicht',
            new_name='en_pol_control_device_stack_height',
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_chromium_hex_discharge',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_chromium_hex_name_location',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_chromium_hex_source',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_chromium_hex_treatment',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_residual_cloride_discharge',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_residual_cloride_name_location',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_residual_cloride_source',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_residual_cloride_treatment',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
