# Generated by Django 2.2 on 2023-05-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0002_t_ec_industries_t12_drainage_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='additional_info',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
