# Generated by Django 4.2.6 on 2024-08-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0002_t_ec_industries_t1_general_revocation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ndi_login_temp',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
