# Generated by Django 4.2.6 on 2025-01-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0002_t_payment_details_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_workflow_dtls',
            name='service_type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='t_workflow_dtls_audit',
            name='service_type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
