# Generated by Django 4.2.6 on 2025-03-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0003_t_workflow_dtls_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='establishment_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_payment_details',
            name='cancelled_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
