# Generated by Django 2.2 on 2023-05-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0003_t_ec_industries_t1_general_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='additional_info_letter',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
