# Generated by Django 4.1.3 on 2023-02-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0003_t_ec_industries_t8_forest_produce_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_ec_industries_t4_project_product',
            name='installed_capacity',
        ),
        migrations.AddField(
            model_name='t_ec_industries_t4_project_product',
            name='name_location_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
