# Generated by Django 4.2.6 on 2024-08-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0003_t_ndi_login_temp_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_payment_details',
            name='service_type',
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='cancelled_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='cancelled_reason',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='remarks',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
