# Generated by Django 4.2.6 on 2025-11-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0004_delete_t_ec_industries_t10_hazardous_chemicals_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general',
            name='establishment_type',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general_audit',
            name='establishment_type',
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='establishment_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='project_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general_audit',
            name='establishment_name',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general_audit',
            name='project_name',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='activity',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general_audit',
            name='activity',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
