# Generated by Django 4.2.6 on 2025-05-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0004_t_ec_industries_t1_general_establishment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='service_id',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
