# Generated by Django 4.1.3 on 2023-02-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0004_remove_t_ec_industries_t4_project_product_installed_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_ec_industries_t2_partner_details',
            name='partner_cid',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
