# Generated by Django 4.2.6 on 2024-09-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0004_remove_t_payment_details_service_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='is_revoked',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
