# Generated by Django 4.1.3 on 2023-02-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0005_alter_t_ec_industries_t2_partner_details_partner_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='establishment_type',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
