# Generated by Django 4.2.6 on 2025-06-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0005_alter_t_ec_industries_t1_general_service_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general_audit',
            name='others_area_acre',
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general_audit',
            name='others_area',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
