# Generated by Django 2.2 on 2023-05-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0005_auto_20230502_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_ec_industries_t11_ec_details',
            name='ec_terms',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
