# Generated by Django 4.2.6 on 2025-11-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0005_remove_t_ec_industries_t1_general_establishment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='proponent_type',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
