# Generated by Django 4.1.3 on 2023-02-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0006_t_ec_industries_t1_general_establishment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='production_process_flow',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='total_area_acre',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
