# Generated by Django 4.2.6 on 2025-11-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0006_t_ec_industries_t1_general_proponent_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general',
            name='applicant_type',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general',
            name='form_type',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general_audit',
            name='applicant_type',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general_audit',
            name='form_type',
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general_audit',
            name='proponent_type',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
