# Generated by Django 4.2.6 on 2025-06-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0006_remove_t_ec_industries_t1_general_audit_others_area_acre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general_audit',
            name='others_area',
        ),
    ]
