# Generated by Django 2.2 on 2023-05-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0007_auto_20230502_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_ec_industries_t13_dumpyard',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('dumpyard_number', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('dumpyard_capacity', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('dumpyard_area', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('dumpyard_location', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='t_ec_industries_t11_ec_details',
            name='ec_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t6_ancillary_road',
            name='dzongkhag',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t6_ancillary_road',
            name='gewog',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t6_ancillary_road',
            name='village',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
