# Generated by Django 4.1.3 on 2023-02-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0007_t_ec_industries_t1_general_production_process_flow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_ec_industries_t10_hazardous_chemicals',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('chemical_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('qty', models.IntegerField(blank=True, default=None, null=True)),
                ('storage_method', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_ec_industries_t9_products_by_products',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('product_type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('qty', models.IntegerField(blank=True, default=None, null=True)),
                ('storage_method', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
