# Generated by Django 4.2.6 on 2025-06-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0007_remove_t_ec_industries_t1_general_audit_others_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general_audit',
            name='others_area',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
