# Generated by Django 4.2.6 on 2025-12-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0007_remove_t_ec_industries_t1_general_applicant_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_payment_details',
            name='application_no',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
