# Generated by Django 2.2 on 2023-05-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0008_auto_20230519_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_renewal_t1',
            name='action_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_renewal_t2',
            name='action_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_renewal_t2',
            name='application_no',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_renewal_t2',
            name='application_status',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
