# Generated by Django 4.1.3 on 2023-02-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0008_t_ec_industries_t10_hazardous_chemicals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='cid',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
