# Generated by Django 4.2.6 on 2025-12-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0008_t_payment_details_application_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_ec_additional_information',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('additional_info_ca', models.TextField(blank=True, default=None, max_length=250, null=True)),
                ('additional_info_ca_date', models.DateField(blank=True, default=None, null=True)),
                ('additional_info_proponent', models.TextField(blank=True, default=None, max_length=250, null=True)),
                ('additional_info_proponent_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='project_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general_audit',
            name='project_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
