# Generated by Django 4.2.6 on 2025-12-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0009_t_ec_additional_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general',
            name='additional_info_letter',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general',
            name='assigned_date',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general',
            name='ec_approval_committee',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general',
            name='ec_type',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general',
            name='establishment_name',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general',
            name='fines_penalties',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general',
            name='fines_penalties_remarks',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general',
            name='inspection_date',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general',
            name='inspection_team',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general_audit',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general_audit',
            name='additional_info_letter',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general_audit',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general_audit',
            name='assigned_date',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general_audit',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general_audit',
            name='ec_approval_committee',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general_audit',
            name='ec_type',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general_audit',
            name='establishment_name',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general_audit',
            name='fines_penalties',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general_audit',
            name='fines_penalties_remarks',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general_audit',
            name='inspection_date',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general_audit',
            name='inspection_team',
        ),
        migrations.RemoveField(
            model_name='t_ec_industries_t1_general_audit',
            name='recommendation',
        ),
    ]
