# Generated by Django 4.1.3 on 2023-02-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0009_alter_t_ec_industries_t1_general_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='total_water_consumption',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='total_water_recycled',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
