# Generated by Django 2.2 on 2023-06-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0009_auto_20230520_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='dzongkhag_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='gewog_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='village_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
