# Generated by Django 4.2.6 on 2025-06-08 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0009_remove_t_ec_industries_t1_general_audit_others_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_ec_industries_t1_general',
            old_name='others_area',
            new_name='others_area_temp',
        ),
    ]
