# Generated by Django 4.1.3 on 2023-03-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0010_t_ec_industries_t1_general_total_water_consumption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_workflow_dtls',
            old_name='status_id',
            new_name='application_status',
        ),
        migrations.RenameField(
            model_name='t_workflow_dtls_audit',
            old_name='status_id',
            new_name='application_status',
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_air_humidity',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_air_rainfall',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_air_temperature',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_air_wind_direction',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_air_wind_speed',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_ambient_bod',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_ambient_cod',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_ambient_conductivity',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_ambient_fauna',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_ambient_flora',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_ambient_ph',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_ambient_tds',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_ambient_tss',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_co_sampling_location',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_co_sampling_location_one',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_co_sampling_location_two',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_eb_sampling_location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_geo_coordinates_sampling_location',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_geo_coordinates_sampling_location_one',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_geo_coordinates_sampling_location_two',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_nb_sampling_location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_nox_sampling_location',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_nox_sampling_location_one',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_nox_sampling_location_two',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_other_poll_sampling_location',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_other_poll_sampling_location_one',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_other_poll_sampling_location_two',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_others_sampling_location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_rpm_sampling_location',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_rpm_sampling_location_one',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_rpm_sampling_location_two',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_sb_sampling_location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_so2_sampling_location',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_so2_sampling_location_one',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_so2_sampling_location_two',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_socio_income_source',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_socio_settlement_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_socio_total_population',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_tpsm_sampling_location',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_tpsm_sampling_location_one',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_tpsm_sampling_location_two',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bl_wb_sampling_location',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='instrument_no',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_workflow_dtls',
            name='ca_authority',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_workflow_dtls',
            name='dzongkhag_thromde_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_workflow_dtls_audit',
            name='ca_authority',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_workflow_dtls_audit',
            name='dzongkhag_thromde_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
