# Generated by Django 4.2.6 on 2025-06-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0010_rename_others_area_t_ec_industries_t1_general_others_area_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_ec_industries_t1_general',
            old_name='others_area_temp',
            new_name='others_area',
        ),
    ]
