# Generated by Django 4.2.23 on 2025-07-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0011_rename_others_area_temp_t_ec_industries_t1_general_others_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general_audit',
            name='water_resources_info',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
