# Generated by Django 4.1.3 on 2023-03-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0011_rename_status_id_t_workflow_dtls_application_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_workflow_dtls',
            name='application_status',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='t_workflow_dtls_audit',
            name='application_status',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
