# Generated by Django 4.2.6 on 2025-07-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0011_rename_others_area_temp_t_ec_industries_t1_general_others_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='water_resources_info',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general_audit',
            name='water_resources_info',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t10_hazardous_chemicals',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='total_water_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='total_water_recycled',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general_audit',
            name='total_water_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general_audit',
            name='total_water_recycled',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t3_machine_equipment',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t5_raw_materials',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t8_forest_produce',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t9_products_by_products',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
