# Generated by Django 2.2 on 2023-07-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0012_auto_20230709_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='ai_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='tat',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
