# Generated by Django 4.2.6 on 2025-07-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0012_t_ec_industries_t1_general_water_resources_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='stripping_ratio',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general_audit',
            name='stripping_ratio',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
