# Generated by Django 4.1.3 on 2023-03-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0012_alter_t_workflow_dtls_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='abstraction_type',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='actual_mineable_area',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='blast_frequency_time',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='blast_location',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='blast_qty',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='blast_required',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='blast_type',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='borewell_depth_dec',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='borewell_depth_feb',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='borewell_depth_jan',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='borewell_installed_capacity',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='borewell_width_depth',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='box_culvert',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='box_drain_length',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bridge_length',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bridge_width',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='bridges',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='capacity_stp',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='construction_substation',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='cross_drains',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='dimension_stp',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='extracted_material_vol',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='formation_width',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='geo_coordinates',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='land_form',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='length_of_transmission',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='location_transmission',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='machineries_type_number',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='max_evacuation_depth',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='maximum_road_gradient',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='month_season_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='pavement_material',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='pavement_width',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='power_generation',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='project_beneficiaries',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='project_output',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='proposed_route_reason',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='restoration_plan',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='right_of_way',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='road_length',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='road_row_width',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='sewerage_quantity',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='sewerage_water_source_distance',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='side_drain',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='side_drain_dimensions',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='side_drain_length',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='sludge_quantity_mgt_plan',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='starting_point',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='starting_point_transmission',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='terminating_point',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='total_buildup_acre',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='total_requirement',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='transmission_area',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='transmission_numbers',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='transmission_termination_point',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='transmission_voltage_level',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_fecal_discharge',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_fecal_source',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_fecal_treatment',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='water_excavated_muck',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t4_project_product',
            name='quantity_annum',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
