# Generated by Django 4.2.23 on 2025-07-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0013_t_ec_industries_t1_general_water_resources_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='total_water_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='total_water_recycled',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general_audit',
            name='total_water_consumption',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general_audit',
            name='total_water_recycled',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
