# Generated by Django 4.1.3 on 2023-03-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0013_t_ec_industries_t1_general_abstraction_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_ec_industries_t11_ec_details',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ec_heading', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('ec_content', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='ec_expiry_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
