# Generated by Django 2.2 on 2023-07-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0013_auto_20230710_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='broad_activity_code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='category',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='specific_activity_code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
