# Generated by Django 4.2.23 on 2025-07-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0014_alter_t_ec_industries_t1_general_total_water_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_ec_industries_t10_hazardous_chemicals',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t3_machine_equipment',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t5_raw_materials',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t8_forest_produce',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t9_products_by_products',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
