# Generated by Django 2.2 on 2023-07-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0015_auto_20230717_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='dzongkhag_thromde',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
