# Generated by Django 4.2.23 on 2025-07-25 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0012_t_ec_industries_t1_general_water_resources_info_and_more'),
        ('proponent', '0015_alter_t_ec_industries_t10_hazardous_chemicals_qty_and_more'),
    ]

    operations = [
    ]
