# Generated by Django 4.2.23 on 2025-07-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0016_merge_20250725_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='stripping_ratio',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general_audit',
            name='stripping_ratio',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
