# Generated by Django 2.2 on 2023-07-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0016_t_ec_industries_t1_general_dzongkhag_thromde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_ec_industries_t1_general',
            old_name='dzongkhag_thromde',
            new_name='dzongkhag_throm',
        ),
    ]
