# Generated by Django 4.2.23 on 2025-07-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0013_alter_t_ec_industries_t1_general_stripping_ratio_and_more'),
        ('proponent', '0017_alter_t_ec_industries_t1_general_stripping_ratio_and_more'),
    ]

    operations = [
    ]
