# Generated by Django 2.2 on 2023-08-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0017_auto_20230718_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='tor_application_no',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
