# Generated by Django 4.2.23 on 2025-07-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0018_merge_20250730_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='thromde_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general_audit',
            name='thromde_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
