# Generated by Django 2.2 on 2023-08-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0018_t_ec_industries_t1_general_tor_application_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='tor_clearance_no',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
