# Generated by Django 4.2.6 on 2025-08-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0019_alter_t_ec_industries_t1_general_thromde_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t10_hazardous_chemicals',
            name='service_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t13_dumpyard',
            name='service_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t2_partner_details',
            name='service_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t3_machine_equipment',
            name='service_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t4_project_product',
            name='service_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t5_raw_materials',
            name='service_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t8_forest_produce',
            name='service_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t9_products_by_products',
            name='service_type',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
