# Generated by Django 4.2.4 on 2023-09-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0019_t_ec_industries_t1_general_tor_clearance_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_ammonia_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_arsenic_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_bod_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_boron_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_cadmium_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_chromium_hex_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_chromium_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_cloride_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_cod_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_colour_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_copper_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_cyanide_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_floride_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_iron_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_lead_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_manganese_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_mercury_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_nickel_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_nitrate_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_oil_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_ph_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_phenolic_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_phosphate_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_residual_cloride_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_s_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_selenium_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_so4_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_tds_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_temp_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_tkn_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_tss_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='waste_water_zinc_source',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
