# Generated by Django 4.2.6 on 2023-11-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0020_alter_t_ec_industries_t1_general_waste_water_ammonia_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='anc_other_asphalt_plant',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='anc_other_bridge',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='anc_other_concrete_building',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='anc_other_housing_colony',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='anc_other_ropeway',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='anc_power_excavation',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
