# Generated by Django 4.2.6 on 2023-12-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0021_t_ec_industries_t1_general_anc_other_asphalt_plant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='road_length',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
