# Generated by Django 4.2.6 on 2023-12-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0022_alter_t_ec_industries_t1_general_road_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='alternative_adequate_justification',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='alternative_capital_expenditure',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_ec_industries_t1_general',
            name='alternative_surface_water',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
