# Generated by Django 4.2.6 on 2024-02-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0025_rename_establishment_type_t_ec_industries_t1_general_establishment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_ec_industries_t1_general',
            old_name='record_Id',
            new_name='record_id',
        ),
    ]
