# Generated by Django 4.2.6 on 2024-04-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0028_t_ec_industries_t1_general_audit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_payment_details',
            old_name='application_date',
            new_name='instrument_date',
        ),
        migrations.RenameField(
            model_name='t_payment_details',
            old_name='account_head_code',
            new_name='issuing_bank',
        ),
        migrations.RenameField(
            model_name='t_payment_details',
            old_name='application_no',
            new_name='journal_no',
        ),
        migrations.RenameField(
            model_name='t_payment_details',
            old_name='application_type',
            new_name='payable_bank',
        ),
        migrations.RenameField(
            model_name='t_payment_details',
            old_name='ec_no',
            new_name='payment_advice_no',
        ),
        migrations.RenameField(
            model_name='t_payment_details',
            old_name='payment_type',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='t_payment_details',
            old_name='proponent_name',
            new_name='payment_mode',
        ),
        migrations.RenameField(
            model_name='t_payment_details',
            old_name='transaction_no',
            new_name='payment_order_no',
        ),
        migrations.RenameField(
            model_name='t_payment_details',
            old_name='transaction_date',
            new_name='payment_request_date',
        ),
        migrations.RenameField(
            model_name='t_payment_details',
            old_name='validity',
            new_name='response_date',
        ),
        migrations.RemoveField(
            model_name='t_payment_details',
            name='amount',
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='agency_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='message',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='mobile_no',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='payer_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='ref_no',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='status_description',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='tax_payer_document_no',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='tax_payer_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='tax_payer_no',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='total_payable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='transaction_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
