# Generated by Django 4.2.6 on 2024-04-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0029_rename_application_date_t_payment_details_instrument_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_payment_details',
            name='payment_advice_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='payment_advice_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='payment_advice_status',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='receipt_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='receipt_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='t_payment_details',
            name='total_receipt_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
