# Generated by Django 4.2.6 on 2024-04-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0030_t_payment_details_payment_advice_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_ec_industries_t1_general',
            name='ca_authority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_ec_industries_t1_general_audit',
            name='ca_authority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_workflow_dtls',
            name='ca_authority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_workflow_dtls_audit',
            name='ca_authority',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
