# Generated by Django 4.2.6 on 2024-04-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0031_alter_t_ec_industries_t1_general_ca_authority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_payment_details',
            name='response_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
