# Generated by Django 4.2.6 on 2024-04-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0032_alter_t_payment_details_response_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_payment_details',
            name='instrument_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_payment_details',
            name='receipt_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
