# Generated by Django 4.2.6 on 2024-04-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0033_alter_t_payment_details_instrument_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_payment_details',
            name='receipt_no',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
