# Generated by Django 4.2.6 on 2024-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proponent', '0034_alter_t_payment_details_receipt_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_payment_details',
            name='service_type',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
