from django.core.files.storage import FileSystemStorage
from django.db import models

fs = FileSystemStorage()

class t_ec_industries_t1_general(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100,default=None, blank=True, null=True)
    application_date = models.DateField(default=None, blank=True, null=True)
    application_type = models.CharField(max_length=100,default=None, blank=True, null=True)
    ca_authority = models.IntegerField(default=None, blank=True, null=True)
    applicant_id = models.CharField(max_length=100,default=None, blank=True, null=True)
    colour_code = models.CharField(max_length=100,default=None, blank=True, null=True)
    applicant_name = models.CharField(max_length=100,default=None, blank=True, null=True)
    address = models.CharField(max_length=250,default=None, blank=True, null=True)
    cid = models.BigIntegerField(default=None, blank=True, null=True)
    contact_no = models.IntegerField(default=None, blank=True, null=True)
    email = models.CharField(max_length=250,default=None, blank=True, null=True)
    project_name = models.TextField(default=None, blank=True, null=True)
    focal_person = models.CharField(max_length=250,default=None, blank=True, null=True)
    establishment_name = models.CharField(max_length=250, default=None, blank=True, null=True)
    thromde_id = models.IntegerField(default=None, blank=True, null=True)
    dzongkhag_code  = models.IntegerField(default=None, blank=True, null=True)
    gewog_code = models.IntegerField(default=None, blank=True, null=True)
    village_code = models.IntegerField(default=None, blank=True, null=True)
    location_name = models.CharField(max_length=250, default=None, blank=True, null=True)
    fee = models.DecimalField(max_digits=10, decimal_places=2, default=None, blank=True, null=True)
    assigned_to = models.CharField(max_length=250,default=None, blank=True, null=True)
    assigned_date = models.DateField(default=None, blank=True, null=True)
    assigned_by = models.CharField(max_length=250,default=None, blank=True, null=True)
    inspection_date = models.DateField(default=None, blank=True, null=True)
    inspection_team = models.TextField(max_length=250, default=None, blank=True, null=True)
    recommendation = models.TextField(max_length=250, default=None, blank=True, null=True)
    ec_type = models.CharField(max_length=250,default=None, blank=True, null=True)
    ec_reference_no = models.CharField(max_length=250,default=None, blank=True, null=True)
    prev_ec_reference_no = models.CharField(max_length=250,default=None, blank=True, null=True)
    action_date = models.DateField(default=None, blank=True, null=True)
    ec_approve_date = models.DateField(default=None, blank=True, null=True)
    ec_expiry_date = models.DateField(default=None, blank=True, null=True)
    ec_approval_committee = models.TextField(max_length=250, default=None, blank=True, null=True)
    fines_penalties = models.CharField(max_length=3,default=None, blank=True, null=True)
    fines_penalties_remarks = models.CharField(max_length=255,default=None, blank=True, null=True)
    application_status = models.CharField(max_length=20,default=None, blank=True, null=True)
    resubmit_remarks = models.TextField(max_length=250, default=None, blank=True, null=True)
    resubmit_date = models.DateField(default=None, blank=True, null=True)
    service_id = models.IntegerField(default=1, blank=True)
    application_source = models.CharField(max_length=20,default=None, blank=True, null=True)
    service_type = models.CharField(max_length=100,default=None, blank=True, null=True)
    additional_info = models.TextField(max_length=250, default=None, blank=True, null=True)
    additional_info_letter = models.TextField(max_length=250, default=None, blank=True, null=True)
    tor_approve_date =  models.DateField(default=None, blank=True, null=True)
    tor_remarks =  models.CharField(max_length=250,default=None, blank=True, null=True)
    ai_date = models.DateField(default=None, blank=True, null=True)
    tat = models.CharField(max_length=100,default=None, blank=True, null=True)
    dzongkhag_throm = models.CharField(max_length=100, default=None, blank=True, null=True)
    tor_application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    tor_clearance_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    revocation_id = models.CharField(max_length=100,default=None, blank=True, null=True)
    is_revoked = models.CharField(max_length=100,default=None, blank=True, null=True)
    activity = models.TextField(default=None, blank=True, null=True)
    proponent_type = models.IntegerField(default=None, blank=True, null=True)

class t_ec_industries_t1_general_audit(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    application_date = models.DateField(default=None, blank=True, null=True)
    application_type = models.CharField(max_length=100, default=None, blank=True, null=True)
    ca_authority = models.IntegerField(default=None, blank=True, null=True)
    applicant_id = models.CharField(max_length=100, default=None, blank=True, null=True)
    colour_code = models.CharField(max_length=100, default=None, blank=True, null=True)
    applicant_name = models.CharField(max_length=100, default=None, blank=True, null=True)
    address = models.CharField(max_length=250, default=None, blank=True, null=True)
    cid = models.BigIntegerField(default=None, blank=True, null=True)
    contact_no = models.IntegerField(default=None, blank=True, null=True)
    email = models.CharField(max_length=250, default=None, blank=True, null=True)
    project_name = models.TextField(default=None, blank=True, null=True)
    focal_person = models.CharField(max_length=250, default=None, blank=True, null=True)
    establishment_name = models.CharField(max_length=250, default=None, blank=True, null=True)
    thromde_id = models.IntegerField(default=None, blank=True, null=True)
    dzongkhag_code = models.IntegerField(default=None, blank=True, null=True)
    gewog_code = models.IntegerField(default=None, blank=True, null=True)
    village_code = models.IntegerField(default=None, blank=True, null=True)
    location_name = models.CharField(max_length=250, default=None, blank=True, null=True)
    fee = models.DecimalField(max_digits=10, decimal_places=2, default=None, blank=True, null=True)
    assigned_to = models.CharField(max_length=250, default=None, blank=True, null=True)
    assigned_date = models.DateField(default=None, blank=True, null=True)
    assigned_by = models.CharField(max_length=250, default=None, blank=True, null=True)
    inspection_date = models.DateField(default=None, blank=True, null=True)
    inspection_team = models.TextField(max_length=250, default=None, blank=True, null=True)
    recommendation = models.TextField(max_length=250, default=None, blank=True, null=True)
    ec_type = models.CharField(max_length=250, default=None, blank=True, null=True)
    ec_reference_no = models.CharField(max_length=250, default=None, blank=True, null=True)
    prev_ec_reference_no = models.CharField(max_length=250, default=None, blank=True, null=True)
    action_date = models.DateField(default=None, blank=True, null=True)
    ec_approve_date = models.DateField(default=None, blank=True, null=True)
    ec_expiry_date = models.DateField(default=None, blank=True, null=True)
    ec_approval_committee = models.TextField(max_length=250, default=None, blank=True, null=True)
    fines_penalties = models.CharField(max_length=3, default=None, blank=True, null=True)
    fines_penalties_remarks = models.CharField(max_length=255, default=None, blank=True, null=True)
    application_status = models.CharField(max_length=20, default=None, blank=True, null=True)
    resubmit_remarks = models.TextField(max_length=250, default=None, blank=True, null=True)
    resubmit_date = models.DateField(default=None, blank=True, null=True)
    service_id = models.IntegerField(default=1, blank=True)
    application_source = models.CharField(max_length=20, default=None, blank=True, null=True)
    service_type = models.CharField(max_length=100, default=None, blank=True, null=True)
    additional_info = models.TextField(max_length=250, default=None, blank=True, null=True)
    additional_info_letter = models.TextField(max_length=250, default=None, blank=True, null=True)
    tor_approve_date = models.DateField(default=None, blank=True, null=True)
    tor_remarks = models.CharField(max_length=250, default=None, blank=True, null=True)
    ai_date = models.DateField(default=None, blank=True, null=True)
    tat = models.CharField(max_length=100, default=None, blank=True, null=True)
    dzongkhag_throm = models.CharField(max_length=100, default=None, blank=True, null=True)
    tor_application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    tor_clearance_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    revocation_id = models.CharField(max_length=100, default=None, blank=True, null=True)
    is_revoked = models.CharField(max_length=100, default=None, blank=True, null=True)
    activity = models.TextField(default=None, blank=True, null=True)
    proponent_type = models.IntegerField(default=None, blank=True, null=True)
    
class t_ec_industries_t11_ec_details(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    ec_type = models.CharField(max_length=100, default=None, blank=True, null=True)
    ec_heading = models.CharField(max_length=250,default=None, blank=True, null=True)
    ec_terms = models.TextField(default=None, blank=True, null=True)
    ec_reference_no = models.CharField(max_length=250,default=None, blank=True, null=True)
    service_type = models.CharField(max_length=255, default=None, blank=True, null=True)

class t_ec_renewal_t1(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    ec_reference_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    proponent_name = models.CharField(max_length=100, default=None, blank=True, null=True)
    address = models.CharField(max_length=250, default=None, blank=True, null=True)
    initiatives_undertaken = models.TextField(default=None, blank=True, null=True)
    fines_penalties = models.CharField(max_length=3, default=None, blank=True, null=True)
    remarks = models.TextField(default=None, blank=True, null=True)
    submission_date = models.DateField(default=None, blank=True, null=True)
    application_status = models.CharField(max_length=20,default=None, blank=True, null=True)
    action_date = models.DateField(default=None, blank=True, null=True)

class t_ec_renewal_t2(models.Model):
    record_id = models.AutoField(primary_key=True)
    ec_reference_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    ec_heading = models.CharField(max_length=250,default=None, blank=True, null=True)
    ec_terms = models.TextField(default=None, blank=True, null=True)
    action_undertaken = models.TextField(default=None, blank=True, null=True)
    remarks = models.TextField(default=None, blank=True, null=True)
    application_status = models.CharField(max_length=20,default=None, blank=True, null=True)
    action_date = models.DateField(default=None, blank=True, null=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    
class t_fines_penalties(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    fines_penalties_type = models.CharField(max_length=100, default=None, blank=True, null=True)
    fines_date = models.DateField(default=None, blank=True, null=True)
    ec_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    proponent_name = models.CharField(max_length=100, default=None, blank=True, null=True)
    address = models.CharField(max_length=250, default=None, blank=True, null=True)
    validity = models.DateField(default=None, blank=True, null=True)
    amount = models.IntegerField(default=None, blank=True, null=True)
    fines_status = models.CharField(max_length=10, default=None, blank=True, null=True)

class t_payment_details(models.Model):
    record_id = models.AutoField(primary_key=True)
    ref_no = models.CharField(max_length=50,default=None, blank=True, null=True)
    payment_request_date = models.DateField(default=None, blank=True, null=True)
    agency_code = models.CharField(max_length=50,default=None, blank=True, null=True)
    payer_email = models.EmailField(default=None, blank=True, null=True)
    mobile_no = models.CharField(max_length=50,default=None, blank=True, null=True)
    total_payable_amount = models.DecimalField(max_digits=10, decimal_places=2,default=None, blank=True, null=True)
    payment_due_date = models.DateField(null=True, blank=True)
    tax_payer_name = models.CharField(max_length=100,default=None, blank=True, null=True)
    tax_payer_document_no = models.CharField(max_length=100,default=None, blank=True, null=True)
    tax_payer_no = models.CharField(max_length=100,default=None, blank=True, null=True)
    response_date = models.DateTimeField(default=None, blank=True, null=True)
    payment_advice_no = models.CharField(max_length=100,default=None, blank=True, null=True)
    message = models.TextField(default=None, blank=True, null=True)
    payment_method = models.CharField(max_length=100,default=None, blank=True, null=True)
    payment_mode = models.CharField(max_length=100,default=None, blank=True, null=True)
    instrument_no = models.CharField(max_length=100,default=None, blank=True, null=True)
    instrument_date = models.DateTimeField(default=None, blank=True, null=True)
    issuing_bank = models.CharField(max_length=100,default=None, blank=True, null=True)
    payable_bank = models.CharField(max_length=100,default=None, blank=True, null=True)
    transaction_id = models.CharField(max_length=100,default=None, blank=True, null=True)
    payment_order_no = models.CharField(max_length=100,default=None, blank=True, null=True)
    journal_no = models.CharField(max_length=100,default=None, blank=True, null=True)
    status_description = models.CharField(max_length=100,default=None, blank=True, null=True)
    description = models.CharField(max_length=255,default=None, blank=True, null=True)
    payment_advice_amount = models.DecimalField(max_digits=10, decimal_places=2,default=None, blank=True, null=True)
    payment_advice_amount_paid = models.DecimalField(max_digits=10, decimal_places=2,default=None, blank=True, null=True)
    payment_advice_status = models.CharField(max_length=255,default=None, blank=True, null=True)
    receipt_no = models.CharField(max_length=255,default=None, blank=True, null=True)
    receipt_date = models.DateTimeField(default=None, blank=True, null=True)
    total_receipt_amount = models.DecimalField(max_digits=10, decimal_places=2,default=None, blank=True, null=True)
    service_type = models.CharField(max_length=255, default=None, blank=True, null=True)
    cancelled_date = models.DateField(default=None, blank=True, null=True)
    cancelled_reason = models.CharField(max_length=255,default=None, blank=True, null=True)
    remarks = models.CharField(max_length=255,default=None, blank=True, null=True)

class t_workflow_dtls(models.Model):
    instance_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    service_id = models.IntegerField(default=None, blank=True, null=True)
    application_status = models.CharField(max_length=10, default=None, blank=True, null=True)
    action_date = models.DateField(default=None, blank=True, null=True)
    actor_id = models.IntegerField(default=None, blank=True, null=True)
    actor_name = models.CharField(max_length=100, default=None, blank=True, null=True)
    assigned_user_id = models.CharField(max_length=20, default=None, blank=True, null=True)
    assigned_role_id = models.CharField(max_length=10, default=None, blank=True, null=True)
    assigned_role_name = models.CharField(max_length=250, default=None, blank=True, null=True)
    ca_authority = models.IntegerField(default=None, blank=True, null=True)
    result = models.CharField(max_length=250, default=None, blank=True, null=True)
    application_source = models.CharField(max_length=20,default=None, blank=True, null=True)
    service_type = models.CharField(max_length=20,default=None, blank=True, null=True)

class t_workflow_dtls_audit(models.Model):
    instance_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    service_id = models.IntegerField(default=None, blank=True, null=True)
    application_status = models.CharField(max_length=10, default=None, blank=True, null=True)
    action_date = models.DateField(default=None, blank=True, null=True)
    actor_id = models.IntegerField(default=None, blank=True, null=True)
    actor_name = models.CharField(max_length=100, default=None, blank=True, null=True)
    assigned_user_id = models.CharField(max_length=20, default=None, blank=True, null=True)
    assigned_role_id = models.CharField(max_length=10, default=None, blank=True, null=True)
    assigned_role_name = models.CharField(max_length=250, default=None, blank=True, null=True)
    ca_authority = models.IntegerField(default=None, blank=True, null=True)
    result = models.CharField(max_length=250, default=None, blank=True, null=True)
    application_source = models.CharField(max_length=20,default=None, blank=True, null=True)
    service_type = models.CharField(max_length=20,default=None, blank=True, null=True)

# ReportSubmission
class t_report_submission_t1(models.Model):
    record_id = models.AutoField(primary_key=True)
    report_type = models.CharField(max_length=100, blank=True, null=True)
    report_reference_no = models.CharField(max_length=100, blank=True, null=True)
    ec_clearance_no = models.CharField(max_length=100, blank=True, null=True)
    ca_authority = models.IntegerField(blank=True, null=True)
    proponent_name = models.CharField(max_length=100, blank=True, null=True)
    address = models.CharField(max_length=250, blank=True, null=True)
    submission_date = models.DateField(default=None, blank=True, null=True)
    submission_year = models.IntegerField(blank=True, null=True)
    initiatives_undertaken = models.TextField(default=None, blank=True, null=True)
    remarks = models.TextField(default=None, blank=True, null=True)
    report_status = models.CharField(max_length=20, blank=True, null=True)
    created_by = models.CharField(max_length=100, blank=True, null=True)
    created_date = models.DateField(blank=True, null=True)

class t_report_submission_t2(models.Model):
    record_id = models.AutoField(primary_key=True)
    report_reference_no = models.CharField(max_length=100, blank=True, null=True)
    ec_terms = models.TextField(default=None, blank=True, null=True)
    action_taken = models.TextField(default=None, blank=True, null=True)
    remarks = models.TextField(default=None, blank=True, null=True)

class t_ndi_login_temp(models.Model):
    record_id = models.AutoField(primary_key=True)
    thread_id = models.CharField(max_length=100, blank=True, null=True)
    category = models.CharField(max_length=100, blank=True, null=True)
    revocation_id = models.CharField(max_length=100, blank=True, null=True)
    created_date = models.DateField(blank=True, null=True)
    session_id = models.CharField(max_length=255, blank=True, null=True)


