from django.core.files.storage import FileSystemStorage
from django.db import models

fs = FileSystemStorage()

class t_ec_industries_t1_general(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100,default=None, blank=True, null=True)
    application_date = models.DateField(default=None, blank=True, null=True)
    application_type = models.CharField(max_length=100,default=None, blank=True, null=True)
    form_type = models.CharField(max_length=250, default=None, blank=True, null=True)
    ca_authority = models.CharField(max_length=100,default=None, blank=True, null=True)
    applicant_id = models.CharField(max_length=100,default=None, blank=True, null=True)
    applicant_type = models.CharField(max_length=100,default=None, blank=True, null=True)
    colour_code = models.CharField(max_length=100,default=None, blank=True, null=True)
    project_name = models.TextField(max_length=250, default=None, blank=True, null=True)
    project_category = models.CharField(max_length=100,default=None, blank=True, null=True)
    applicant_name = models.CharField(max_length=100,default=None, blank=True, null=True)
    address = models.CharField(max_length=250,default=None, blank=True, null=True)
    cid = models.BigIntegerField(default=None, blank=True, null=True)
    contact_no = models.IntegerField(default=None, blank=True, null=True)
    email = models.CharField(max_length=250,default=None, blank=True, null=True)
    focal_person = models.CharField(max_length=250,default=None, blank=True, null=True)
    industry_type = models.CharField(max_length=250,default=None, blank=True, null=True)
    establishment_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    industry_classification = models.CharField(max_length=250,default=None, blank=True, null=True)
    thromde_id = models.CharField(max_length=10,default=None, blank=True, null=True)
    dzongkhag_code  = models.IntegerField(default=None, blank=True, null=True)
    gewog_code = models.IntegerField(default=None, blank=True, null=True)
    village_code = models.IntegerField(default=None, blank=True, null=True)
    location_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    industrial_area_acre = models.IntegerField(default=None, blank=True, null=True)
    state_reserve_forest_acre = models.IntegerField(default=None, blank=True, null=True)
    private_area_acre = models.IntegerField(default=None, blank=True, null=True)
    others_area_acre = models.IntegerField(default=None, blank=True, null=True)
    total_area_acre = models.IntegerField(default=None, blank=True, null=True)
    green_area_acre = models.IntegerField(default=None, blank=True, null=True)
    total_buildup_acre = models.IntegerField(default=None, blank=True, null=True)
    production_process_flow = models.TextField(max_length=500, default=None, blank=True, null=True)
    proposed_location_justification = models.TextField(max_length=250, default=None, blank=True, null=True)
    terrain_elevation = models.IntegerField(default=None, blank=True, null=True)
    terrain_slope = models.CharField(max_length=250,default=None, blank=True, null=True)
    project_objective = models.TextField(max_length=250, default=None, blank=True, null=True)
    project_no_of_workers = models.IntegerField(default=None, blank=True, null=True)
    project_cost = models.IntegerField(default=None, blank=True, null=True)
    project_duration = models.CharField(max_length=250,default=None, blank=True, null=True)
    project_output = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_protected_area_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_protected_area_distance = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_migratory_route_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_migratory_route_distance = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_wetland_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_wetland_distance = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_water_bodies_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_water_bodies_distance = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_fmu_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_fmu_distance = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_agricultural_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_agricultural_distance = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_settlement_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_settlement_distance = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_road_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_road_distance = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_public_infra_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_public_infra_distance = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_school_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_school_distance = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_heritage_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_heritage_distance = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_tourist_facility_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_tourist_facility_distance = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_impt_installation_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_impt_installation_distance = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_industries_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_industries_distance = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_others = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_others_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_others_distance = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_tpsm_sampling_location_one = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_tpsm_sampling_location_two = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_tpsm_sampling_location = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_rpm_sampling_location_one = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_rpm_sampling_location_two = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_rpm_sampling_location = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_so2_sampling_location_one = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_so2_sampling_location_two = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_so2_sampling_location = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_nox_sampling_location_one = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_nox_sampling_location_two = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_nox_sampling_location = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_co_sampling_location_one = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_co_sampling_location_two = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_co_sampling_location = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_other_poll_sampling_location_one = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_other_poll_sampling_location_two = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_other_poll_sampling_location = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_geo_coordinates_sampling_location_one = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_geo_coordinates_sampling_location_two = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_geo_coordinates_sampling_location = models.CharField(max_length=250,default=None, blank=True, null=True)
    bl_air_temperature = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_air_humidity = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_air_rainfall = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_air_wind_direction = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_air_wind_speed = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_nb_sampling_location = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_sb_sampling_location = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_eb_sampling_location = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_wb_sampling_location = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_others_sampling_location = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_ambient_ph = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_ambient_tss = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_ambient_tds = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_ambient_conductivity = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_ambient_bod = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_ambient_cod = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_ambient_flora = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_ambient_fauna = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_socio_settlement_name = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_socio_total_population = models.CharField(max_length=100,default=None, blank=True, null=True)
    bl_socio_income_source = models.CharField(max_length=100,default=None, blank=True, null=True)
    technology_used = models.CharField(max_length=250,default=None, blank=True, null=True)
    technology_no = models.CharField(max_length=250,default=None, blank=True, null=True)
    technology_total_capacity = models.CharField(max_length=250,default=None, blank=True, null=True)
    energy_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    energy_source_justification = models.TextField(max_length=250, default=None, blank=True, null=True)
    water_required = models.CharField(max_length=250,default=None, blank=True, null=True)
    water_raw_material_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    water_raw_material_qty_day = models.IntegerField(default=None, blank=True, null=True)
    water_raw_material_recycle_day = models.IntegerField(default=None, blank=True, null=True)
    water_cleaning_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    water_cleaning_qty_day = models.IntegerField(default=None, blank=True, null=True)
    water_cleaning_recycle_day = models.IntegerField(default=None, blank=True, null=True)
    water_process_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    water_process_qty_day = models.IntegerField(default=None, blank=True, null=True)
    water_process_recycle_day = models.IntegerField(default=None, blank=True, null=True)
    water_domestic_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    water_domestic_qty_day = models.IntegerField(default=None, blank=True, null=True)
    water_domestic_recycle_day = models.IntegerField(default=None, blank=True, null=True)
    water_dust_compression_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    water_dust_compression_qty_day = models.IntegerField(default=None, blank=True, null=True)
    water_dust_compression_recycle_day = models.IntegerField(default=None, blank=True, null=True)
    water_others_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    water_others_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    water_others_qty_day = models.IntegerField(default=None, blank=True, null=True)
    water_others_recycle_day = models.IntegerField(default=None, blank=True, null=True)
    water_provide_by_iestate = models.CharField(max_length=250,default=None, blank=True, null=True)
    total_water_consumption = models.IntegerField(default=None, blank=True, null=True)
    total_water_recycled = models.IntegerField(default=None, blank=True, null=True)
    water_excavated_muck = models.CharField(max_length=10,default=None, blank=True, null=True)
    water_downstream_users = models.TextField(max_length=250, default=None, blank=True, null=True)
    water_flow_rate_lean = models.CharField(max_length=250,default=None, blank=True, null=True)
    water_source_distance = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_road_required = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_road_length = models.IntegerField(default=None, blank=True, null=True)
    anc_road_start_point = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_road_end_point = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_road_blast_required = models.CharField(max_length=3,default=None, blank=True, null=True)
    anc_road_blast_type = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_road_blast_qty = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_road_blast_location = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_road_blast_frequency_time = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_power_line_required = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_power_line_voltage = models.IntegerField(default=None, blank=True, null=True)
    anc_power_line_length = models.IntegerField(default=None, blank=True, null=True)
    anc_power_line_start_point = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_power_line_end_point = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_power_line_storing_method = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_other_required = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_other_crushing_unit = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_other_surface_collection = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_other_ground_water = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_other_mineral = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_other_general = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_other_transmission = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_other_concrete_building = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_other_bridge = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_other_asphalt_plant = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_other_housing_colony = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_other_ropeway = models.CharField(max_length=250,default=None, blank=True, null=True)
    anc_power_excavation = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_impact_allocated_budget = models.IntegerField(default=None, blank=True, null=True)
    en_impact_hazardous_waste_list = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_impact_hazardous_waste_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_impact_hazardous_waste_qty_annum = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_impact_hazardous_waste_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_impact_non_hazardous_waste_list = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_impact_non_hazardous_waste_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_impact_non_hazardous_waste_qty_annum = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_impact_non_hazardous_waste_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_impact_medical_waste_list = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_impact_medical_waste_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_impact_medical_waste_qty_annum = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_impact_medical_waste_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_impact_ewaste_list = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_impact_ewaste_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_impact_ewaste_qty_annum = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_impact_ewaste_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_impact_others_waste_list = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_impact_others_waste_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_impact_others_waste_qty_annum = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_impact_others_waste_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_waste_water_generate = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_nh3n_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_nh3n_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_nh3n_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_nh3n_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_arsenic_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_arsenic_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_arsenic_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_arsenic_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_bod_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_bod_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_bod_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_bod_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_boron_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_boron_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_boron_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_boron_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_cadmium_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_cadmium_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_cadmium_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_cadmium_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_cod_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_cod_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_cod_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_cod_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_cloride_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_cloride_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_cloride_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_cloride_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_chromium_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_chromium_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_chromium_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_chromium_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_chromium_hex_source = models.CharField(max_length=250, default=None, blank=True, null=True)
    waste_water_chromium_hex_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_chromium_hex_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_chromium_hex_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_copper_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_copper_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_copper_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_copper_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_cyanide_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_cyanide_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_cyanide_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_cyanide_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_floride_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_floride_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_floride_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_floride_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_phosphate_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_phosphate_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_phosphate_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_phosphate_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_nitrate_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_nitrate_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_nitrate_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_nitrate_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_iron_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_iron_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_iron_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_iron_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_lead_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_lead_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_lead_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_lead_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_manganese_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_manganese_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_manganese_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_manganese_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_mercury_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_mercury_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_mercury_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_mercury_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_nickel_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_nickel_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_nickel_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_nickel_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_oil_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_oil_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_oil_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_oil_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_ph_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_ph_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_ph_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_ph_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_phenolic_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_phenolic_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_phenolic_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_phenolic_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_selenium_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_selenium_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_selenium_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_selenium_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_so4_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_so4_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_so4_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_so4_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_s_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_s_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_s_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_s_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_tds_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_tds_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_tds_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_tds_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_tss_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_tss_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_tss_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_tss_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_temp_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_temp_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_temp_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_temp_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_tkn_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_tkn_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_tkn_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_tkn_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_residual_cloride_source = models.CharField(max_length=250, default=None, blank=True, null=True)
    waste_water_residual_cloride_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_residual_cloride_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_residual_cloride_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_zinc_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_zinc_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_zinc_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_zinc_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_ammonia_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_ammonia_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_ammonia_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_ammonia_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_colour_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_colour_discharge = models.IntegerField(default=None, blank=True, null=True)
    waste_water_colour_treatment = models.IntegerField(default=None, blank=True, null=True)
    waste_water_colour_name_location = models.TextField(max_length=250, default=None, blank=True, null=True)
    waste_water_treatment_plant_capacity = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_qty_per_annum = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_treatment_plant_etp = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_treatment_sludge_qty = models.CharField(max_length=250,default=None, blank=True, null=True)
    waste_water_treatment_plant_name_location = models.CharField(max_length=255,default=None, blank=True, null=True)
    waste_water_fecal_source = models.CharField(max_length=255,default=None, blank=True, null=True)
    waste_water_fecal_discharge = models.CharField(max_length=255,default=None, blank=True, null=True)
    waste_water_fecal_treatment = models.CharField(max_length=255,default=None, blank=True, null=True)
    en_industry_emission_generate = models.CharField(max_length=3,default=None, blank=True, null=True)
    en_spm_emission_expected = models.IntegerField(default=None, blank=True, null=True)
    en_so2_emission_expected = models.IntegerField(default=None, blank=True, null=True)
    en_nox_emission_expected = models.IntegerField(default=None, blank=True, null=True)
    en_co_emission_expected = models.IntegerField(default=None, blank=True, null=True)
    en_fluoride_emission_expected = models.IntegerField(default=None, blank=True, null=True)
    en_pol_control_device_stack_height = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_pol_control_device_stack_diameter = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_pol_control_device_dimension = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_pol_control_device_volume = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_pol_control_device_temp = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_air_pollution_control_device_capacity = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_air_pollution_control_pcd_dimension = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_noise_ind_area_day = models.IntegerField(default=None, blank=True, null=True)
    en_noise_ind_area_night = models.IntegerField(default=None, blank=True, null=True)
    en_noise_ind_area_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_noise_sen_area_day = models.IntegerField(default=None, blank=True, null=True)
    en_noise_sen_area_night = models.IntegerField(default=None, blank=True, null=True)
    en_noise_sen_area_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_noise_mixed_area_day = models.IntegerField(default=None, blank=True, null=True)
    en_noise_mixed_area_night = models.IntegerField(default=None, blank=True, null=True)
    en_noise_mixed_area_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_other_impact_odour_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_odour_qty = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_odour_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_other_impact_fugutive_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_fugutive_qty = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_fugutive_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_other_impact_slope_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_slope_qty = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_slope_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_other_impact_aesthetic_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_aesthetic_qty = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_aesthetic_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_other_impact_mucks_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_mucks_qty = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_mucks_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_other_impact_sewerage_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_sewerage_qty = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_sewerage_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_other_impact_erosion_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_erosion_qty = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_erosion_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_other_impact_storm_water_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_storm_water_qty = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_storm_water_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_other_impact_habitat_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_habitat_qty = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_habitat_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_other_impact_socio_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_socio_qty = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_socio_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_other_impact_water_source_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_water_source_qty = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_water_source_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    en_other_impact_other_source = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_other_qty = models.CharField(max_length=250,default=None, blank=True, null=True)
    en_other_impact_other_mgt_plan = models.TextField(max_length=250, default=None, blank=True, null=True)
    project_beneficiaries = models.CharField(max_length=250,default=None, blank=True, null=True)
    proposed_route_reason = models.CharField(max_length=250,default=None, blank=True, null=True)
    right_of_way = models.CharField(max_length=250,default=None, blank=True, null=True)
    length_of_transmission = models.CharField(max_length=250,default=None, blank=True, null=True)
    transmission_voltage_level = models.CharField(max_length=250,default=None, blank=True, null=True)
    starting_point_transmission = models.CharField(max_length=250,default=None, blank=True, null=True)
    transmission_termination_point = models.CharField(max_length=250,default=None, blank=True, null=True)
    construction_substation = models.CharField(max_length=250,default=None, blank=True, null=True)
    transmission_numbers = models.CharField(max_length=250,default=None, blank=True, null=True)
    transmission_area = models.CharField(max_length=250,default=None, blank=True, null=True)
    location_transmission = models.CharField(max_length=250,default=None, blank=True, null=True)
    power_generation = models.CharField(max_length=100,default=None, blank=True, null=True)
    restoration_plan = models.CharField(max_length=250,default=None, blank=True, null=True)
    max_evacuation_depth = models.CharField(max_length=250,default=None, blank=True, null=True)
    month_season_name = models.CharField(max_length=100,default=None, blank=True, null=True)
    machineries_type_number = models.CharField(max_length=250,default=None, blank=True, null=True)
    abstraction_type = models.CharField(max_length=250,default=None, blank=True, null=True)
    total_requirement = models.CharField(max_length=250,default=None, blank=True, null=True)
    borewell_installed_capacity = models.CharField(max_length=250,default=None, blank=True, null=True)
    geo_coordinates = models.CharField(max_length=250,default=None, blank=True, null=True)
    borewell_width_depth = models.CharField(max_length=250,default=None, blank=True, null=True)
    borewell_depth_dec = models.CharField(max_length=250,default=None, blank=True, null=True)
    borewell_depth_jan = models.CharField(max_length=250,default=None, blank=True, null=True)
    borewell_depth_feb = models.CharField(max_length=250,default=None, blank=True, null=True)
    land_form = models.CharField(max_length=250,default=None, blank=True, null=True)
    actual_mineable_area = models.CharField(max_length=250,default=None, blank=True, null=True)
    blast_required = models.CharField(max_length=3,default=None, blank=True, null=True)
    blast_type = models.CharField(max_length=250,default=None, blank=True, null=True)
    blast_qty = models.CharField(max_length=250,default=None, blank=True, null=True)
    blast_location = models.CharField(max_length=250,default=None, blank=True, null=True)
    blast_frequency_time = models.CharField(max_length=250,default=None, blank=True, null=True)
    road_length = models.IntegerField(default=None, blank=True, null=True)
    starting_point = models.CharField(max_length=250,default=None, blank=True, null=True)
    terminating_point = models.CharField(max_length=250,default=None, blank=True, null=True)
    road_row_width = models.CharField(max_length=250,default=None, blank=True, null=True)
    formation_width = models.CharField(max_length=250,default=None, blank=True, null=True)
    pavement_width = models.CharField(max_length=250,default=None, blank=True, null=True)
    pavement_material = models.CharField(max_length=250,default=None, blank=True, null=True)
    extracted_material_vol = models.CharField(max_length=250,default=None, blank=True, null=True)
    maximum_road_gradient = models.CharField(max_length=250,default=None, blank=True, null=True)
    cross_drains = models.CharField(max_length=250,default=None, blank=True, null=True)
    box_culvert = models.CharField(max_length=250,default=None, blank=True, null=True)
    bridges = models.CharField(max_length=250,default=None, blank=True, null=True)
    bridge_width = models.CharField(max_length=250,default=None, blank=True, null=True)
    bridge_length = models.CharField(max_length=250,default=None, blank=True, null=True)
    side_drain = models.CharField(max_length=250,default=None, blank=True, null=True)
    side_drain_length = models.CharField(max_length=250,default=None, blank=True, null=True)
    side_drain_dimensions = models.CharField(max_length=250,default=None, blank=True, null=True)
    box_drain_length = models.CharField(max_length=250,default=None, blank=True, null=True)
    sewerage_quantity = models.CharField(max_length=250,default=None, blank=True, null=True)
    capacity_stp = models.CharField(max_length=250,default=None, blank=True, null=True)
    dimension_stp = models.CharField(max_length=250,default=None, blank=True, null=True)
    sludge_quantity_mgt_plan = models.CharField(max_length=250,default=None, blank=True, null=True)
    sewerage_water_source_distance = models.CharField(max_length=250,default=None, blank=True, null=True)
    project_location_site = models.CharField(max_length=200,default=None, blank=True, null=True)
    water_source_ph = models.CharField(max_length=100,default=None, blank=True, null=True)
    water_source_turbidity = models.CharField(max_length=100,default=None, blank=True, null=True)
    water_source_conductivity = models.CharField(max_length=100,default=None, blank=True, null=True)
    water_source_ecoli = models.CharField(max_length=100,default=None, blank=True, null=True)
    fee = models.IntegerField(default=None, blank=True, null=True)
    assigned_to = models.CharField(max_length=250,default=None, blank=True, null=True)
    assigned_date = models.DateField(default=None, blank=True, null=True)
    assigned_by = models.CharField(max_length=250,default=None, blank=True, null=True)
    inspection_date = models.DateField(default=None, blank=True, null=True)
    inspection_team = models.TextField(max_length=250, default=None, blank=True, null=True)
    recommendation = models.TextField(max_length=250, default=None, blank=True, null=True)
    ec_type = models.CharField(max_length=250,default=None, blank=True, null=True)
    ec_reference_no = models.CharField(max_length=250,default=None, blank=True, null=True)
    prev_ec_reference_no = models.CharField(max_length=250,default=None, blank=True, null=True)
    action_date = models.DateField(default=None, blank=True, null=True)
    ec_approve_date = models.DateField(default=None, blank=True, null=True)
    ec_expiry_date = models.DateField(default=None, blank=True, null=True)
    ec_approval_committee = models.TextField(max_length=250, default=None, blank=True, null=True)
    fines_penalties = models.CharField(max_length=3,default=None, blank=True, null=True)
    fines_penalties_remarks = models.CharField(max_length=255,default=None, blank=True, null=True)
    application_status = models.CharField(max_length=20,default=None, blank=True, null=True)
    resubmit_remarks = models.TextField(max_length=250, default=None, blank=True, null=True)
    resubmit_date = models.DateField(default=None, blank=True, null=True)
    service_id = models.IntegerField(default=None, blank=True, null=True)
    application_source = models.CharField(max_length=20,default=None, blank=True, null=True)
    service_type = models.CharField(max_length=100,default=None, blank=True, null=True)
    additional_info = models.TextField(max_length=250, default=None, blank=True, null=True)
    additional_info_letter = models.TextField(max_length=250, default=None, blank=True, null=True)
    tor_approve_date =  models.DateField(default=None, blank=True, null=True)
    tor_remarks =  models.CharField(max_length=250,default=None, blank=True, null=True)
    ai_date = models.DateField(default=None, blank=True, null=True)
    tat = models.CharField(max_length=100,default=None, blank=True, null=True)
    broad_activity_code = models.CharField(max_length=10,default=None, blank=True, null=True)
    specific_activity_code = models.CharField(max_length=10,default=None, blank=True, null=True)
    category = models.TextField(default=None, blank=True, null=True)
    dzongkhag_throm = models.CharField(max_length=100, default=None, blank=True, null=True)
    tor_application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    tor_clearance_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    alternative_surface_water = models.TextField(default=None, blank=True, null=True)
    alternative_capital_expenditure = models.TextField(default=None, blank=True, null=True)
    alternative_adequate_justification = models.TextField(default=None, blank=True, null=True)
    production_capacity = models.IntegerField(default=None, blank=True, null=True)
    stripping_ratio = models.IntegerField(default=None, blank=True, null=True)
    bench_height = models.IntegerField(default=None, blank=True, null=True)
    bench_width = models.IntegerField(default=None, blank=True, null=True)

    
class t_ec_industries_t2_partner_details(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100,default=None, blank=True, null=True)
    partner_type = models.CharField(max_length=100,default=None, blank=True, null=True)
    partner_cid = models.BigIntegerField(default=None, blank=True, null=True)
    partner_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    partner_address = models.CharField(max_length=250,default=None, blank=True, null=True)

class t_ec_industries_t3_machine_equipment(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100,default=None, blank=True, null=True)
    machine_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    qty = models.IntegerField(default=None, blank=True, null=True)
    installed_capacity = models.CharField(max_length=100,default=None, blank=True, null=True)


class t_ec_industries_t4_project_product(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100,default=None, blank=True, null=True)
    product_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    name_location_type = models.CharField(max_length=100, default=None, blank=True, null=True)
    quantity_annum = models.CharField(max_length=100, default=None, blank=True, null=True)
    storage_method = models.CharField(max_length=100,default=None, blank=True, null=True)


class t_ec_industries_t5_raw_materials(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    raw_material = models.CharField(max_length=250,default=None, blank=True, null=True)
    qty = models.IntegerField(default=None, blank=True, null=True)
    source = models.CharField(max_length=250,default=None, blank=True, null=True)
    storage_method = models.CharField(max_length=100,default=None, blank=True, null=True)

class t_ec_industries_t6_ancillary_road(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    road_chainage_from = models.IntegerField(default=None, blank=True, null=True)
    road_chainage_to = models.IntegerField(default=None, blank=True, null=True)
    land_type = models.CharField(max_length=100,default=None, blank=True, null=True)
    terrain = models.CharField(max_length=100,default=None, blank=True, null=True)
    road_width = models.IntegerField(default=None, blank=True, null=True)
    row = models.CharField(max_length=100,default=None, blank=True, null=True)
    area_required = models.IntegerField(default=None, blank=True, null=True)
    dzongkhag = models.CharField(max_length=100,default=None, blank=True, null=True)
    gewog = models.CharField(max_length=100,default=None, blank=True, null=True)
    village = models.CharField(max_length=100,default=None, blank=True, null=True)

class t_ec_industries_t7_ancillary_power_line(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    line_chainage_from = models.IntegerField(default=None, blank=True, null=True)
    line_chainage_to = models.IntegerField(default=None, blank=True, null=True)
    land_type = models.CharField(max_length=100,default=None, blank=True, null=True)
    terrain = models.CharField(max_length=100,default=None, blank=True, null=True)
    tower_type = models.CharField(max_length=100,default=None, blank=True, null=True)
    no_of_tower = models.IntegerField(default=None, blank=True, null=True)
    row = models.CharField(max_length=100,default=None, blank=True, null=True)
    area_required = models.IntegerField(default=None, blank=True, null=True)

class t_ec_industries_t8_forest_produce(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    produce_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    qty = models.IntegerField(default=None, blank=True, null=True)
    storage_method = models.CharField(max_length=100,default=None, blank=True, null=True)

class t_ec_industries_t9_products_by_products(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    product_type = models.CharField(max_length=100,default=None, blank=True, null=True)
    product_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    qty = models.IntegerField(default=None, blank=True, null=True)
    storage_method = models.CharField(max_length=100,default=None, blank=True, null=True)

class t_ec_industries_t10_hazardous_chemicals(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    chemical_name = models.CharField(max_length=250,default=None, blank=True, null=True)
    qty = models.IntegerField(default=None, blank=True, null=True)
    storage_method = models.CharField(max_length=100,default=None, blank=True, null=True)

class t_ec_industries_t11_ec_details(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    ec_type = models.CharField(max_length=100, default=None, blank=True, null=True)
    ec_heading = models.CharField(max_length=250,default=None, blank=True, null=True)
    ec_terms = models.TextField(default=None, blank=True, null=True)
    ec_reference_no = models.CharField(max_length=250,default=None, blank=True, null=True)

class t_ec_industries_t12_drainage_details(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    drain_type = models.CharField(max_length=250,default=None, blank=True, null=True)
    chainage = models.CharField(max_length=250,default=None, blank=True, null=True)

class t_ec_industries_t13_dumpyard(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100,default=None, blank=True, null=True)
    dumpyard_number = models.CharField(max_length=250,default=None, blank=True, null=True)
    dumpyard_capacity = models.CharField(max_length=100, default=None, blank=True, null=True)
    dumpyard_area = models.CharField(max_length=100, default=None, blank=True, null=True)
    dumpyard_location = models.CharField(max_length=100,default=None, blank=True, null=True)


class t_ec_renewal_t1(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    ec_reference_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    proponent_name = models.CharField(max_length=100, default=None, blank=True, null=True)
    address = models.CharField(max_length=250, default=None, blank=True, null=True)
    initiatives_undertaken = models.TextField(default=None, blank=True, null=True)
    fines_penalties = models.CharField(max_length=3, default=None, blank=True, null=True)
    remarks = models.TextField(default=None, blank=True, null=True)
    submission_date = models.DateField(default=None, blank=True, null=True)
    application_status = models.CharField(max_length=20,default=None, blank=True, null=True)
    action_date = models.DateField(default=None, blank=True, null=True)

class t_ec_renewal_t2(models.Model):
    record_id = models.AutoField(primary_key=True)
    ec_reference_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    ec_heading = models.CharField(max_length=250,default=None, blank=True, null=True)
    ec_terms = models.TextField(default=None, blank=True, null=True)
    action_undertaken = models.TextField(default=None, blank=True, null=True)
    remarks = models.TextField(default=None, blank=True, null=True)
    application_status = models.CharField(max_length=20,default=None, blank=True, null=True)
    action_date = models.DateField(default=None, blank=True, null=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    

class t_fines_penalties(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    fines_penalties_type = models.CharField(max_length=100, default=None, blank=True, null=True)
    fines_date = models.DateField(default=None, blank=True, null=True)
    ec_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    proponent_name = models.CharField(max_length=100, default=None, blank=True, null=True)
    address = models.CharField(max_length=250, default=None, blank=True, null=True)
    validity = models.DateField(default=None, blank=True, null=True)
    amount = models.IntegerField(default=None, blank=True, null=True)
    fines_status = models.CharField(max_length=10, default=None, blank=True, null=True)

class t_payment_details(models.Model):
    record_id = models.AutoField(primary_key=True)
    application_type = models.CharField(max_length=100, default=None, blank=True, null=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    application_date = models.DateField(default=None, blank=True, null=True)
    proponent_name = models.CharField(max_length=100, default=None, blank=True, null=True)
    payment_type = models.CharField(max_length=100, default=None, blank=True, null=True)
    ec_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    validity = models.DateField(default=None, blank=True, null=True)
    amount = models.IntegerField(default=None, blank=True, null=True)
    instrument_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    transaction_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    transaction_date = models.DateField(default=None, blank=True, null=True)
    account_head_code = models.CharField(max_length=100, default=None, blank=True, null=True)


class t_workflow_dtls(models.Model):
    instance_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    service_id = models.IntegerField(default=None, blank=True, null=True)
    application_status = models.CharField(max_length=10, default=None, blank=True, null=True)
    action_date = models.DateField(default=None, blank=True, null=True)
    actor_id = models.IntegerField(default=None, blank=True, null=True)
    actor_name = models.CharField(max_length=100, default=None, blank=True, null=True)
    assigned_user_id = models.CharField(max_length=20, default=None, blank=True, null=True)
    assigned_role_id = models.CharField(max_length=10, default=None, blank=True, null=True)
    assigned_role_name = models.CharField(max_length=250, default=None, blank=True, null=True)
    ca_authority = models.CharField(max_length=100, default=None, blank=True, null=True)
    result = models.CharField(max_length=250, default=None, blank=True, null=True)
    application_source = models.CharField(max_length=20,default=None, blank=True, null=True)

class t_workflow_dtls_audit(models.Model):
    instance_id = models.AutoField(primary_key=True)
    application_no = models.CharField(max_length=100, default=None, blank=True, null=True)
    service_id = models.IntegerField(default=None, blank=True, null=True)
    application_status = models.CharField(max_length=3, default=None, blank=True, null=True)
    action_date = models.DateField(default=None, blank=True, null=True)
    actor_id = models.IntegerField(default=None, blank=True, null=True)
    actor_name = models.CharField(max_length=100, default=None, blank=True, null=True)
    assigned_user_id = models.CharField(max_length=20, default=None, blank=True, null=True)
    assigned_role_id = models.CharField(max_length=10, default=None, blank=True, null=True)
    assigned_role_name = models.CharField(max_length=250, default=None, blank=True, null=True)
    ca_authority = models.CharField(max_length=100, default=None, blank=True, null=True)
    dzongkhag_thromde_id = models.CharField(max_length=100, default=None, blank=True, null=True)
    result = models.CharField(max_length=250, default=None, blank=True, null=True)

# ReportSubmission
class t_report_submission_t1(models.Model):
    record_id = models.AutoField(primary_key=True)
    report_type = models.CharField(max_length=100, blank=True, null=True)
    report_reference_no = models.CharField(max_length=100, blank=True, null=True)
    ec_clearance_no = models.CharField(max_length=100, blank=True, null=True)
    ca_authority = models.IntegerField(blank=True, null=True)
    proponent_name = models.CharField(max_length=100, blank=True, null=True)
    address = models.CharField(max_length=250, blank=True, null=True)
    submission_date = models.DateField(default=None, blank=True, null=True)
    submission_year = models.IntegerField(blank=True, null=True)
    initiatives_undertaken = models.TextField(default=None, blank=True, null=True)
    remarks = models.TextField(default=None, blank=True, null=True)
    report_status = models.CharField(max_length=20, blank=True, null=True)
    created_by = models.CharField(max_length=100, blank=True, null=True)
    created_date = models.DateField(blank=True, null=True)

class t_report_submission_t2(models.Model):
    record_id = models.AutoField(primary_key=True)
    report_reference_no = models.CharField(max_length=100, blank=True, null=True)
    ec_terms = models.TextField(default=None, blank=True, null=True)
    action_taken = models.TextField(default=None, blank=True, null=True)
    remarks = models.TextField(default=None, blank=True, null=True)
