from django.conf.urls.static import static
from django.urls import path
from . import views
from ECS import settings


urlpatterns = [
    path('', views.home, name='index'),
    path('login', views.login, name='login'),
    path('user_login', views.user_login, name='user_login'),
    path('add_user', views.add_user, name='add_user'),
    path('manage_menu', views.manage_menu, name='manage_menu'),
    path('manage_submenu', views.manage_submenu, name='manage_submenu'),
    path('add_menu_master', views.add_menu_master, name='add_menu_master'),
    path('add_submenu_master', views.add_submenu_master, name='add_submenu_master'),
    path('user_master', views.user_master, name='user_master'),
    path('client_registration', views.client_registration, name='client_registration'),
    path('manage_user', views.manage_user, name='manage_user'),
    path('check_email_id', views.check_email_id, name='check_email_id'),
    path('logout', views.logout, name='logout'),
    path('account_setting', views.account_setting, name='account_setting'),

    path('change_password', views.change_password, name='change_password'),
    path('check_user_password', views.check_user_password, name='check_user_password'),
    path('change_mobile_number', views.change_mobile_number, name='change_mobile_number'),
    path('load_gewog', views.load_gewog, name='load_gewog'),
    path('load_village', views.load_village, name='load_village'),
    path('new_client_registration', views.new_client_registration, name='new_client_registration'),
    path('registered_client', views.registered_client, name='registered_client'),
    path('manage_client', views.manage_client, name='manage_client'),
    path('update_first_login_details', views.update_first_login_details, name='update_first_login_details'),
    path('get_security_answer', views.get_security_answer, name='get_security_answer'),
    path('update_password', views.update_password, name='update_password'),
    path('load_security_question', views.load_security_question, name='load_security_question'),

    #Menu Details
    path('get_content_details', views.get_content_details, name='get_content_details'),
    path('contact_us', views.contact_us, name='contact_us'),
    path('manage_publications',views.manage_publications, name='manage_publications'),
    path('add_publication_file', views.add_publication_file, name='add_publication_file'),
    path('add_publication_attach', views.add_publication_attach, name='add_publication_attach'),
    path('get_other_details', views.get_other_details, name='get_other_details'),
    path('delete_publication_attachment', views.delete_publication_attachment, name='delete_publication_attachment'),
    path('update_publication_file', views.update_publication_file, name='update_publication_file'),
    path('update_publication_attach', views.update_publication_attach, name='update_publication_attach'),
    path('manage_publication_details', views.manage_publication_details, name='manage_publication_details'),
    path('publications',views.publications, name='publications'),
    path('get_menu_details/<int:menu_id>', views.get_menu_details, name='get_menu_details'),
    path('save_menu_attachment', views.save_menu_attachment, name='save_menu_attachment'),
    path('add_submenu_details',views.add_submenu_details, name='add_submenu_details'),
    path('add_menu_details',views.add_menu_details, name='add_menu_details'),
    path('save_menu_details', views.save_menu_details,name='save_menu_details'),
    path('save_menu_attachment_details', views.save_menu_attachment_details, name='save_menu_attachment_details'),
    path('delete_attachment', views.delete_attachment, name='delete_attachment'),
    path('update_menu_details', views.update_menu_details,name='update_menu_details'),
    path('manage_menu_details', views.manage_menu_details, name='manage_menu_details'),
    path('save_submenu_attachment',views.save_submenu_attachment, name='save_submenu_attachment'),
    path('save_submenu_attachment_details', views.save_submenu_attachment_details, name='save_submenu_attachment_details'),
    path('manage_submenu_details',views.manage_submenu_details, name='manage_submenu_details'),
    path('get_submenu_details/<int:sub_menu_id>', views.get_submenu_details, name='get_submenu_details'),
    path('update_submenu_details', views.update_submenu_details,name='update_submenu_details'),
    path('manage_about_us', views.manage_about_us, name='manage_about_us'),
    path('about_us', views.about_us, name='about_us'),
    path('add_about_us',views.add_about_us, name='add_about_us'),
    path('save_about_us', views.save_about_us, name='save_about_us'),
    path('edit_about_us/<int:about_us_id>', views.edit_about_us, name='edit_about_us'),
    path('update_about_us', views.update_about_us, name='update_about_us'),
    path('manage_about_us_details', views.manage_about_us_details, name='manage_about_us_details'),
    path('show_about_us', views.show_about_us, name='show_about_us'),
    path('track_application', views.track_application, name='track_application'),
    path('manage_notification_circulars', views.manage_notification_circulars, name='manage_notification_circulars'),
    path('notification_circulars',views.notification_circulars, name='notification_circulars'),
    path('manage_notification_details', views.manage_notification_details, name='manage_notification_details'),
    path('get_notification_details', views.get_notification_details, name='get_notification_details'),
    path('add_notification_file', views.add_notification_file, name='add_notification_file'),
    path('add_notification_attach', views.add_notification_attach, name='add_notification_attach'),
    path('delete_notification_attachment', views.delete_notification_attachment, name='delete_notification_attachment'),
    path('update_notification_file', views.update_notification_file, name='update_notification_file'),
    path('update_notification_attach', views.update_notification_attach, name='update_notification_attach'),
    path('manage_committee_schedule',views.manage_committee_schedule, name='manage_committee_schedule'),
    path('manage_eia_related',views.manage_eia_related, name='manage_eia_related'),
    path('manage_live_statistics',views.manage_live_statistics, name='manage_live_statistics'),
    path('manage_home_page', views.manage_home_page, name='manage_home_page'),



    #Master Details
    path('agency_master', views.agency_master, name='agency_master'),
    path('add_agency_master', views.add_agency_master, name='add_agency_master'),
    path('edit_agency_master', views.edit_agency_master, name='edit_agency_master'),
    path('delete_agency_master', views.delete_agency_master, name='delete_agency_master'),
    path('proponent_master', views.proponent_master, name='proponent_master'),
    path('add_proponent_master', views.add_proponent_master, name='add_proponent_master'),
    path('edit_proponent_master', views.edit_proponent_master, name='edit_proponent_master'),
    path('delete_proponent_master', views.delete_proponent_master, name='delete_proponent_master'),
    path('role_master', views.role_master, name='role_master')
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)