# Generated by Django 4.1.3 on 2023-04-09 01:22

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_about_us',
            fields=[
                ('about_us_id', models.AutoField(primary_key=True, serialize=False)),
                ('about_us_title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('about_us_content', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('is_deleted', models.CharField(blank=True, default=None, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_agency_master',
            fields=[
                ('agency_id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_code', models.CharField(max_length=100)),
                ('agency_name', models.CharField(max_length=100)),
                ('agency_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='t_app_status_master',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
                ('status_type', models.CharField(max_length=20)),
                ('status_type_short_desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='t_bsic_code',
            fields=[
                ('bsic_id', models.AutoField(primary_key=True, serialize=False)),
                ('broad_activity_code', models.CharField(max_length=10)),
                ('activity_description', models.CharField(max_length=250)),
                ('specific_activity_code', models.CharField(max_length=10)),
                ('specific_activity_description', models.TextField()),
                ('classification', models.CharField(max_length=10)),
                ('category', models.TextField()),
                ('colour_code', models.CharField(max_length=10)),
                ('competent_authority', models.CharField(max_length=250)),
                ('entry_point', models.CharField(max_length=10)),
                ('service_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='t_country_master',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_dzongkhag_master',
            fields=[
                ('dzongkhag_code', models.AutoField(primary_key=True, serialize=False)),
                ('dzongkhag_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_error_log',
            fields=[
                ('error_code', models.AutoField(primary_key=True, serialize=False)),
                ('error_detail', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_date', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_fees_schedule',
            fields=[
                ('fees_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_id', models.IntegerField()),
                ('service_name', models.CharField(max_length=100)),
                ('parameter', models.CharField(max_length=250)),
                ('rate', models.IntegerField()),
                ('application_fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='t_file_attachment',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('file_path', models.CharField(max_length=250)),
                ('attachment', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='')),
                ('attachment_type', models.CharField(blank=True, max_length=100, null=True)),
                ('document_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_forgot_password',
            fields=[
                ('forgot_pass_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.IntegerField()),
                ('security_question_id', models.IntegerField()),
                ('answer', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='t_gewog_master',
            fields=[
                ('gewog_code', models.AutoField(primary_key=True, serialize=False)),
                ('gewog_name', models.CharField(max_length=100)),
                ('dzongkhag_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecs_admin.t_dzongkhag_master')),
            ],
        ),
        migrations.CreateModel(
            name='t_homepage_master',
            fields=[
                ('homepage_id', models.AutoField(primary_key=True, serialize=False)),
                ('homepage_title', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('homepage_content', models.TextField(blank=True, default=None, max_length=250, null=True)),
                ('is_active', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('document_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.CharField(blank=True, default=None, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_menu_master',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('menu_content', models.TextField(blank=True, default=None, max_length=250, null=True)),
                ('is_active', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('has_sub_menu', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('document_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.CharField(blank=True, default=None, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_notification_details',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('notification_content', models.TextField(blank=True, default=None, null=True)),
                ('document_id', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('is_deleted', models.CharField(blank=True, default=None, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_other_details',
            fields=[
                ('others_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('document_id', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('is_deleted', models.CharField(blank=True, default=None, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_proponent_type_master',
            fields=[
                ('proponent_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('proponent_type_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='t_role_master',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
                ('is_active', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='t_section_master',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=100)),
                ('division_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='t_security_question_master',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_service_master',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_submenu_master',
            fields=[
                ('sub_menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_id', models.IntegerField(blank=True, null=True)),
                ('sub_menu_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('sub_menu_content', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('is_active', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('document_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.CharField(blank=True, default=None, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_thromde_master',
            fields=[
                ('thromde_id', models.AutoField(primary_key=True, serialize=False)),
                ('thromde_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t_user_role_mapping',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('role_id', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='t_user_type_master',
            fields=[
                ('user_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='t_village_master',
            fields=[
                ('village_code', models.AutoField(primary_key=True, serialize=False)),
                ('village_name', models.CharField(max_length=100)),
                ('village_name_dzo', models.CharField(default=None, max_length=100)),
                ('gewog_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecs_admin.t_gewog_master')),
            ],
        ),
        migrations.CreateModel(
            name='t_user_master',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_type', models.TextField(blank=True, default=None, null=True)),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('agency_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('agency_id', models.IntegerField(blank=True, default=None, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('contact_number', models.IntegerField(blank=True, default=None, null=True)),
                ('email_id', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('password', models.TextField(blank=True, default=None, null=True)),
                ('cid', models.BigIntegerField(blank=True, default=None, null=True)),
                ('is_active', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('logical_delete', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('last_login_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('created_on', models.DateField(blank=True, default=None, null=True)),
                ('modified_by', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('modified_on', models.DateField(blank=True, default=None, null=True)),
                ('accept_reject', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('dzongkhag_code', models.IntegerField(blank=True, default=None, null=True)),
                ('gewog_code', models.IntegerField(blank=True, default=None, null=True)),
                ('village_code', models.IntegerField(blank=True, default=None, null=True)),
                ('proponent_type', models.IntegerField(blank=True, default=None, null=True)),
                ('proponent_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('address', models.TextField(blank=True, default=None, max_length=250, null=True)),
                ('role_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecs_admin.t_role_master')),
            ],
        ),
        migrations.CreateModel(
            name='t_location_field_office_mapping',
            fields=[
                ('location_code', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=100)),
                ('competent_authority_id', models.IntegerField(blank=True, default=None, null=True)),
                ('dzongkhag_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecs_admin.t_dzongkhag_master')),
            ],
        ),
        migrations.CreateModel(
            name='t_competant_authority_master',
            fields=[
                ('competent_authority_id', models.AutoField(primary_key=True, serialize=False)),
                ('competent_authority', models.CharField(max_length=100)),
                ('remarks', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('dzongkhag_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecs_admin.t_dzongkhag_master')),
            ],
        ),
    ]
