# Generated by Django 2.2 on 2023-04-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_village_master',
            name='village_name_dzo',
        ),
    ]
