# Generated by Django 4.2.6 on 2024-10-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_village_master',
            name='village_name_dzo',
        ),
    ]
