# Generated by Django 4.2.6 on 2024-07-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0002_remove_t_village_master_village_name_dzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_village_master',
            name='village_name_dzo',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
