# Generated by Django 2.2 on 2023-05-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0003_t_village_master_village_name_dzo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_menu_master',
            name='menu_content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='t_submenu_master',
            name='sub_menu_content',
            field=models.TextField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='t_user_master',
            name='agency_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
