# Generated by Django 4.1.3 on 2023-01-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0003_t_village_master_village_name_dzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_role_master',
            name='is_active',
            field=models.CharField(default=None, max_length=3),
            preserve_default=False,
        ),
    ]
