# Generated by Django 4.2.6 on 2025-11-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0003_t_village_master_village_name_dzo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_bsic_code',
            old_name='category',
            new_name='activity',
        ),
        migrations.RemoveField(
            model_name='t_bsic_code',
            name='activity_description',
        ),
        migrations.RemoveField(
            model_name='t_bsic_code',
            name='broad_activity_code',
        ),
        migrations.RemoveField(
            model_name='t_bsic_code',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='t_bsic_code',
            name='specific_activity_code',
        ),
        migrations.RemoveField(
            model_name='t_bsic_code',
            name='specific_activity_description',
        ),
    ]
