# Generated by Django 4.1.3 on 2023-04-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0003_t_village_master_village_name_dzo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_user_master',
            name='agency_id',
        ),
        migrations.AddField(
            model_name='t_user_master',
            name='agency_code',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
