# Generated by Django 2.2 on 2023-07-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0003_t_village_master_village_name_dzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_notification_details',
            name='notification_date',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
