# Generated by Django 2.2 on 2023-05-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0004_auto_20230515_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_menu_master',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_submenu_master',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
