# Generated by Django 4.2.23 on 2025-11-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0004_rename_category_t_bsic_code_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_bsic_code',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
