# Generated by Django 4.1.3 on 2023-01-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0004_t_role_master_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_menu_master',
            name='is_deleted',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='t_submenu_master',
            name='is_deleted',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
