# Generated by Django 2.2 on 2023-08-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0004_t_notification_details_notification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_bsic_code',
            name='has_tor',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
