# Generated by Django 2.2 on 2023-05-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0005_auto_20230516_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_user_master',
            name='i_dzongkhag',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_user_master',
            name='i_gewog',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='t_user_master',
            name='i_village',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
