# Generated by Django 4.2.4 on 2023-09-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0005_t_bsic_code_has_tor'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_details_master',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_head_name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('account_head_code', models.BigIntegerField(blank=True, default=None, null=True)),
                ('service_fee', models.IntegerField(blank=True, default=None, null=True)),
                ('payment_type', models.CharField(blank=True, default=None, max_length=250, null=True)),
            ],
        ),
    ]
