# Generated by Django 4.1.3 on 2023-01-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0005_t_menu_master_is_deleted_t_submenu_master_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_about_us',
            fields=[
                ('about_us_id', models.AutoField(primary_key=True, serialize=False)),
                ('about_us_title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('about_us_content', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('is_deleted', models.CharField(blank=True, default=None, max_length=3, null=True)),
            ],
        ),
    ]
