# Generated by Django 4.2.6 on 2025-12-04 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0005_t_bsic_code_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_other_details',
            name='type',
            field=models.CharField(blank=True, default='F', max_length=255, null=True),
        ),
    ]
