# Generated by Django 4.1.3 on 2023-01-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0006_t_about_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_notification_details',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('notification_title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('notification_content', models.TextField(blank=True, default=None, null=True)),
                ('document_id', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('is_deleted', models.CharField(blank=True, default=None, max_length=3, null=True)),
            ],
        ),
    ]
