# Generated by Django 4.2.4 on 2023-09-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0006_payment_details_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_details_master',
            name='service_fee',
        ),
    ]
