# Generated by Django 4.2.6 on 2024-03-21 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0007_remove_payment_details_master_service_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_dzongkhag_master',
            old_name='dzongkhag_code',
            new_name='dzongkhag_serial_no',
        ),
        migrations.RenameField(
            model_name='t_gewog_master',
            old_name='gewog_code',
            new_name='gewog_serial_no',
        ),
        migrations.RenameField(
            model_name='t_village_master',
            old_name='village_code',
            new_name='village_serial_no',
        ),
        migrations.RemoveField(
            model_name='t_gewog_master',
            name='dzongkhag_code',
        ),
        migrations.RemoveField(
            model_name='t_village_master',
            name='gewog_code',
        ),
        migrations.RemoveField(
            model_name='t_village_master',
            name='village_name_dzo',
        ),
        migrations.AddField(
            model_name='t_dzongkhag_master',
            name='dzongkhag_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='t_dzongkhag_master',
            name='dzongkhag_name_bh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='t_gewog_master',
            name='dungkhag_serial_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_gewog_master',
            name='dzongkhag_serial_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecs_admin.t_dzongkhag_master'),
        ),
        migrations.AddField(
            model_name='t_gewog_master',
            name='gewog_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='t_gewog_master',
            name='gewog_name_bh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='t_village_master',
            name='chiwog_serial_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_village_master',
            name='gewog_serial_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecs_admin.t_gewog_master'),
        ),
        migrations.AddField(
            model_name='t_village_master',
            name='status',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='t_village_master',
            name='village_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='t_village_master',
            name='village_name_bh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='t_dzongkhag_master',
            name='dzongkhag_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='t_gewog_master',
            name='gewog_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='t_village_master',
            name='village_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
