# Generated by Django 4.1.3 on 2023-01-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0007_t_notification_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_other_details',
            fields=[
                ('others_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('document_id', models.BigIntegerField(blank=True, null=True)),
                ('is_active', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('is_deleted', models.CharField(blank=True, default=None, max_length=3, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='t_publication_details',
        ),
    ]
