# Generated by Django 4.1.3 on 2023-02-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0008_t_other_details_delete_t_publication_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='t_homepage_master',
            fields=[
                ('homepage_id', models.AutoField(primary_key=True, serialize=False)),
                ('homepage_title', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('homepage_content', models.TextField(blank=True, default=None, max_length=250, null=True)),
                ('is_active', models.CharField(blank=True, default=None, max_length=3, null=True)),
                ('document_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.CharField(blank=True, default=None, max_length=3, null=True)),
            ],
        ),
    ]
