# Generated by Django 4.2.6 on 2024-03-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0008_rename_dzongkhag_code_t_dzongkhag_master_dzongkhag_serial_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_dzongkhag_master',
            name='dzongkhag_name_bh',
        ),
        migrations.RemoveField(
            model_name='t_gewog_master',
            name='dungkhag_serial_no',
        ),
        migrations.RemoveField(
            model_name='t_gewog_master',
            name='gewog_name_bh',
        ),
        migrations.RemoveField(
            model_name='t_village_master',
            name='chiwog_serial_no',
        ),
        migrations.RemoveField(
            model_name='t_village_master',
            name='status',
        ),
        migrations.RemoveField(
            model_name='t_village_master',
            name='village_name_bh',
        ),
    ]
