# Generated by Django 4.1.3 on 2023-02-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0009_t_homepage_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_file_attachment',
            name='application_no',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
