# Generated by Django 4.2.6 on 2024-03-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecs_admin', '0011_rename_dzongkhag_code_t_dzongkhag_master_dzongkhag_serial_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_village_master',
            name='chiwog_serial_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='t_village_master',
            name='status',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
